# Práctica 1.1 — Probabilidad y Estadística
## Análisis de la evolución poblacional mundial

### Objetivo

Utilizar un conjunto de datos real para comprobar el funcionamiento del entorno de análisis de datos y aplicar medidas estadísticas descriptivas básicas utilizando Pandas y NumPy.

## Actividad 1. Identificación de la fuente
### Propósito

Reconocer la procedencia del conjunto de datos antes de utilizarlo y documentar correctamente su fuente.

### Fuente de datos

Los datos utilizados en esta práctica provienen de **Our World in Data (OWID)**.

La fuente original es **United Nations, World Population Prospects (2024)**.

**Cita:**

> UN, World Population Prospects (2024) – processed by Our World in Data. “Annual change in population – UN WPP” [dataset]. United Nations, “World Population Prospects”; United Nations, “World Population Prospects - Interim Update” [original data].

### Preguntas

**1. ¿Quién produjo originalmente los datos?**

**2. ¿Qué organización los procesa para su utilización en Our World in Data?**

**3. ¿Qué representa la variable que analizarás?**

# Actividad 2 — Carga y exploración de datos

### Propósito

Comprobar que el entorno de Python, Pandas y Jupyter funciona correctamente y realizar una primera exploración del conjunto de datos.

In [1]:
import pandas as pd
import numpy as np

In [133]:
df = pd.read_csv("../data/raw/annual-population-growth/annual-population-growth.csv")

In [73]:
df.head(3)

,Entity,Code,Year,Annual change in population,Annual population change (Projected)
0,Afghanistan,AFG,1951,103163.0,NaN
1,Afghanistan,AFG,1952,108441.0,NaN
2,Afghanistan,AFG,1953,108919.0,NaN

In [74]:
df.tail()

,Entity,Code,Year,Annual change in population,Annual population change (Projected)
38395,Zimbabwe,ZWE,2096,NaN,100752.0
38396,Zimbabwe,ZWE,2097,NaN,91796.0
38397,Zimbabwe,ZWE,2098,NaN,87605.0
38398,Zimbabwe,ZWE,2099,NaN,76670.0
38399,Zimbabwe,ZWE,2100,NaN,70019.0

In [5]:
df.shape

(38400, 5)

In [7]:
df.columns.tolist()

['Entity',
 'Code',
 'Year',
 'Annual change in population',
 'Annual population change (Projected)']

In [52]:
df.dtypes

Entity                                      str
Code                                        str
Year                                      int64
Annual change in population             float64
Annual population change (Projected)    float64
dtype: object

In [53]:
df.describe()

,Year,Annual change in population,Annual population change (Projected)
count,38400.000000,1.868800e+04,1.971200e+04
mean,2025.500000,2.063019e+06,8.375481e+05
std,43.300872,9.440859e+06,5.816745e+06
min,1951.000000,-3.315935e+06,-2.291035e+07
25%,1988.000000,1.781000e+03,-9.742750e+03
50%,2025.500000,4.689800e+04,9.350000e+01
75%,2063.000000,3.021128e+05,1.411160e+05
max,2100.000000,9.337137e+07,7.206736e+07

In [54]:
df.isnull().sum()

Entity                                      0
Code                                     1200
Year                                        0
Annual change in population             19712
Annual population change (Projected)    18688
dtype: int64

In [ ]:
df["Entity"].nunique()

256

### Preguntas

**1. ¿Cuántas filas y columnas tiene el dataset?**

**2. ¿Qué tipo de datos contiene la variable `Year`?**

**3. ¿Existen valores faltantes?**

**4. ¿Cuántas entidades diferentes contiene el dataset?**

# Actividad 3 — Estadística descriptiva

### Propósito

Aplicar medidas estadísticas básicas a la variable histórica de cambio anual de población.

Hagamos un filtro para obtener un data frame que corresponda a los datos de la Entidad "Mexico" y que sean datos a partir de 1980.

In [55]:
df.head(3)

,Entity,Code,Year,Annual change in population,Annual population change (Projected)
0,Afghanistan,AFG,1951,103163.0,NaN
1,Afghanistan,AFG,1952,108441.0,NaN
2,Afghanistan,AFG,1953,108919.0,NaN

In [134]:
df_extraccion_entity = df[["Entity","Year"]]
df_extraccion_entity

            Entity  Year
0      Afghanistan  1951
1      Afghanistan  1952
2      Afghanistan  1953
3      Afghanistan  1954
4      Afghanistan  1955
...            ...   ...
38395     Zimbabwe  2096
38396     Zimbabwe  2097
38397     Zimbabwe  2098
38398     Zimbabwe  2099
38399     Zimbabwe  2100

[38400 rows x 2 columns]

In [80]:
df_2020 = df[df["Year"]==2020 ]
df_2020.head(3)

,Entity,Code,Year,Annual change in population,Annual population change (Projected)
69,Afghanistan,AFG,2020,1212852.0,NaN
219,Africa (UN),UN_AFR,2020,32815675.0,NaN
369,Albania,ALB,2020,-13061.0,NaN

In [82]:
df_2020_ext_col1 = df_2020[["Entity","Year"]]
df_2020_ext_col1.head(3)
df_2020_ext_col2 = df[df["Year"]==2020 ][["Entity","Year"]]
df_2020_ext_col2.shape

(256, 2)

In [87]:
df_2005_2020 = df[ (df["Year"] >= 2005) & (df["Year"] <= 2020) & (df["Entity"] == "Mexico")]
df_2005_2020.shape

(16, 5)

In [84]:
df_2005_2020.head(3)

,Entity,Code,Year,Annual change in population,Annual population change (Projected)
54,Afghanistan,AFG,2005,843919.0,NaN
55,Afghanistan,AFG,2006,1019525.0,NaN
56,Afghanistan,AFG,2007,485752.0,NaN

In [88]:
df_ext_EA = df_2005_2020[["Entity","Annual change in population"]]
df_ext_EA.head(3)

       Entity  Annual change in population
22254  Mexico                    1417373.0
22255  Mexico                    1442162.0
22256  Mexico                    1520690.0

In [89]:
df_ext_EA.mean(numeric_only=True)

Annual change in population    1400307.625
dtype: float64

In [ ]:
df_mex.mean(numeric_only=True)

Year                           2.001500e+03
Annual change in population    1.456611e+06
dtype: float64

In [32]:
anio_consultado = 2020

In [138]:
df_new = df[["Entity"]]
df_new

            Entity
0      Afghanistan
1      Afghanistan
2      Afghanistan
3      Afghanistan
4      Afghanistan
...            ...
38395     Zimbabwe
38396     Zimbabwe
38397     Zimbabwe
38398     Zimbabwe
38399     Zimbabwe

[38400 rows x 1 columns]

In [141]:
df.loc[:,["Entity","Year"]]

            Entity  Year
0      Afghanistan  1951
1      Afghanistan  1952
2      Afghanistan  1953
3      Afghanistan  1954
4      Afghanistan  1955
...            ...   ...
38395     Zimbabwe  2096
38396     Zimbabwe  2097
38397     Zimbabwe  2098
38398     Zimbabwe  2099
38399     Zimbabwe  2100

[38400 rows x 2 columns]

In [176]:
df.loc[20000:35000]

,Entity,Code,Year,Annual change in population,Annual population change (Projected)
20000,Low-income countries,OWID_LIC,2001,10677553.0,NaN
20001,Low-income countries,OWID_LIC,2002,11913571.0,NaN
20002,Low-income countries,OWID_LIC,2003,12406252.0,NaN
20003,Low-income countries,OWID_LIC,2004,12305744.0,NaN
20004,Low-income countries,OWID_LIC,2005,12772824.0,NaN
...,...,...,...,...,...
34996,Turkey,TUR,1997,901834.0,NaN
34997,Turkey,TUR,1998,881417.0,NaN
34998,Turkey,TUR,1999,857531.0,NaN
34999,Turkey,TUR,2000,834041.0,NaN
35000,Turkey,TUR,2001,819168.0,NaN

In [148]:
df.iloc[10000]

Entity                                  Equatorial Guinea
Code                                                  GNQ
Year                                                 2051
Annual change in population                           NaN
Annual population change (Projected)              46407.0
Name: 10000, dtype: object

In [149]:
df.loc[:,["Entity","Year","Annual change in population"]]

            Entity  Year  Annual change in population
0      Afghanistan  1951                     103163.0
1      Afghanistan  1952                     108441.0
2      Afghanistan  1953                     108919.0
3      Afghanistan  1954                     111251.0
4      Afghanistan  1955                     119027.0
...            ...   ...                          ...
38395     Zimbabwe  2096                          NaN
38396     Zimbabwe  2097                          NaN
38397     Zimbabwe  2098                          NaN
38398     Zimbabwe  2099                          NaN
38399     Zimbabwe  2100                          NaN

[38400 rows x 3 columns]

In [151]:
df.loc[10000,["Entity","Year","Annual change in population"]]

Entity                         Equatorial Guinea
Year                                        2051
Annual change in population                  NaN
Name: 10000, dtype: object

In [ ]:
dff = df[(df["Year"]>=2005) & (df["Year"]<=2023) & (df["Entity"]=="Mexico")]

In [170]:
dff = df[(df["Year"]>=2005) & (df["Year"]<=2023) & (df["Entity"] == "Mexico")][["Annual change in population"]]
dff.head()

       Annual change in population
22254                    1417373.0
22255                    1442162.0
22256                    1520690.0
22257                    1599930.0
22258                    1625434.0

In [172]:
print(dff.mean())
print(dff.median())
print(dff.var())
print(dff.std())
print(dff.min())
print(dff.max())

Annual change in population    1.333981e+06
dtype: float64
Annual change in population    1417373.0
dtype: float64
Annual change in population    6.061445e+10
dtype: float64
Annual change in population    246200.028553
dtype: float64
Annual change in population    849098.0
dtype: float64
Annual change in population    1625434.0
dtype: float64

In [166]:
df_mex.columns.to_list()

['Entity', 'Year', 'Annual change in population']

1.	¿Cuál es el valor de la media?  1 333 981
2.	¿Cuál es el valor de la mediana?  1 417 373
3.	¿Cuál es el valor de la desviación estándar? 246 200
4.	¿Qué entidad presenta el valor mínimo y cuál el máximo? minimo 849 098 
máximo 1 625 434

In [177]:
df.loc[df["Entity"]=="Morocco"]

,Entity,Code,Year,Annual change in population,Annual population change (Projected)
23400,Morocco,MAR,1951,223837.0,NaN
23401,Morocco,MAR,1952,235589.0,NaN
23402,Morocco,MAR,1953,244689.0,NaN
23403,Morocco,MAR,1954,253748.0,NaN
23404,Morocco,MAR,1955,264811.0,NaN
...,...,...,...,...,...
23545,Morocco,MAR,2096,NaN,-218584.0
23546,Morocco,MAR,2097,NaN,-221679.0
23547,Morocco,MAR,2098,NaN,-224698.0
23548,Morocco,MAR,2099,NaN,-227985.0
23549,Morocco,MAR,2100,NaN,-231150.0

**Variable de análisis**

In [173]:
import sys

print("Python:", sys.version)
print("Pandas:", pd.__version__)
print("NumPy:", np.__version__)

Python: 3.12.0 (v3.12.0:0fb18b02c8, Oct  2 2023, 09:45:56) [Clang 13.0.0 (clang-1300.0.29.30)]
Pandas: 3.0.5
NumPy: 2.5.2

In [165]:
df_mex_acp_2020 = df_anio_consultado[["Annual change in population"]]

In [164]:
cambio_poblacion_anio_consultado = df_anio_consultado["Annual change in population"]

In [53]:
type(cambio_poblacion_anio_consultado)

pandas.Series

### Calcular los estadísticos

In [37]:
media = cambio_poblacion_anio_consultado.mean()
mediana = cambio_poblacion_anio_consultado.median()
varianza = cambio_poblacion_anio_consultado.var()
desviacion_estandar = cambio_poblacion_anio_consultado.std()
minimo = cambio_poblacion_anio_consultado.min()
maximo = cambio_poblacion_anio_consultado.max()

print("Media:", media)
print("Mediana:", mediana)
print("Varianza:", varianza)
print("Desviación estándar:", desviacion_estandar)
print("Mínimo:", minimo)
print("Máximo:", maximo)

Media: 1036075.0
Mediana: 1036075.0
Varianza: nan
Desviación estándar: nan
Mínimo: 1036075.0
Máximo: 1036075.0

### Encontrar las entidades con mínimo y máximo

In [62]:
fila_minimo = df_anio_consultado.loc[df_anio_consultado["Annual change in population"].idxmin()]
fila_maximo = df_anio_consultado.loc[df_anio_consultado["Annual change in population"].idxmax()]

print("Entidad con el valor mínimo:", fila_minimo["Entity"])
print("Valor mínimo:", fila_minimo["Annual change in population"])

print("Entidad con el valor máximo:", fila_maximo["Entity"])
print("Valor máximo:", fila_maximo["Annual change in population"])

Entidad con el valor mínimo: Venezuela
Valor mínimo: -494016.0
Entidad con el valor máximo: World
Valor máximo: 75707590.0

In [63]:
print(fila_maximo)

Entity                                       World
Code                                      OWID_WRL
Year                                          2020
Annual change in population             75707590.0
Annual population change (Projected)           NaN
Name: 37869, dtype: object

In [64]:
print(fila_minimo)

Entity                                  Venezuela
Code                                          VEN
Year                                         2020
Annual change in population             -494016.0
Annual population change (Projected)          NaN
Name: 37269, dtype: object

### Preguntas

**1. ¿Cuál es el valor de la media?**

**2. ¿Cuál es el valor de la mediana?**

**3. ¿Cuál es el valor de la desviación estándar?**

**4. ¿Qué entidad presenta el valor mínimo y cuál el máximo?**

# Actividad 4 — Comprobación del entorno

### Propósito

Comprobar que el notebook está utilizando correctamente las herramientas configuradas para la práctica.

In [65]:
import sys

print("Python:", sys.version)
print("Pandas:", pd.__version__)
print("NumPy:", np.__version__)

Python: 3.12.0 (v3.12.0:0fb18b02c8, Oct  2 2023, 09:45:56) [Clang 13.0.0 (clang-1300.0.29.30)]
Pandas: 3.0.5
NumPy: 2.5.2

# Resultados

En esta práctica se cargó y exploró un conjunto de datos reales sobre el cambio anual de población. Se identificó la fuente de los datos, se revisó la estructura del DataFrame y se calcularon medidas estadísticas descriptivas para un año seleccionado.

También se comprobaron las versiones de Python, Pandas y NumPy utilizadas por el notebook.

In [92]:
df.head()

,Entity,Code,Year,Annual change in population,Annual population change (Projected)
0,Afghanistan,AFG,1951,103163.0,NaN
1,Afghanistan,AFG,1952,108441.0,NaN
2,Afghanistan,AFG,1953,108919.0,NaN
3,Afghanistan,AFG,1954,111251.0,NaN
4,Afghanistan,AFG,1955,119027.0,NaN

In [105]:
df.loc[600:610,["Entity","Year"]]

             Entity  Year
600  American Samoa  1951
601  American Samoa  1952
602  American Samoa  1953
603  American Samoa  1954
604  American Samoa  1955
605  American Samoa  1956
606  American Samoa  1957
607  American Samoa  1958
608  American Samoa  1959
609  American Samoa  1960
610  American Samoa  1961

In [107]:
df.iloc[10000]

Entity                                  Equatorial Guinea
Code                                                  GNQ
Year                                                 2051
Annual change in population                           NaN
Annual population change (Projected)              46407.0
Name: 10000, dtype: object

In [108]:
df.loc[:,["Entity","Year","Annual change in population"]]

            Entity  Year  Annual change in population
0      Afghanistan  1951                     103163.0
1      Afghanistan  1952                     108441.0
2      Afghanistan  1953                     108919.0
3      Afghanistan  1954                     111251.0
4      Afghanistan  1955                     119027.0
...            ...   ...                          ...
38395     Zimbabwe  2096                          NaN
38396     Zimbabwe  2097                          NaN
38397     Zimbabwe  2098                          NaN
38398     Zimbabwe  2099                          NaN
38399     Zimbabwe  2100                          NaN

[38400 rows x 3 columns]

In [111]:
df.iloc[:,[0,2,3]]

            Entity  Year  Annual change in population
0      Afghanistan  1951                     103163.0
1      Afghanistan  1952                     108441.0
2      Afghanistan  1953                     108919.0
3      Afghanistan  1954                     111251.0
4      Afghanistan  1955                     119027.0
...            ...   ...                          ...
38395     Zimbabwe  2096                          NaN
38396     Zimbabwe  2097                          NaN
38397     Zimbabwe  2098                          NaN
38398     Zimbabwe  2099                          NaN
38399     Zimbabwe  2100                          NaN

[38400 rows x 3 columns]

In [112]:
df.loc[10000,["Entity","Year","Annual change in population"]]

Entity                         Equatorial Guinea
Year                                        2051
Annual change in population                  NaN
Name: 10000, dtype: object

In [113]:
df.iloc[10000,[0,2,3]]

Entity                         Equatorial Guinea
Year                                        2051
Annual change in population                  NaN
Name: 10000, dtype: object

In [114]:
df.loc[(df["Entity"]== "Mexico") & (df["Year"]== 2000)]

,Entity,Code,Year,Annual change in population,Annual population change (Projected)
22249,Mexico,MEX,2000,1509843.0,NaN

In [120]:
df.iloc[22249]

Entity                                     Mexico
Code                                          MEX
Year                                         2000
Annual change in population             1509843.0
Annual population change (Projected)          NaN
Name: 22249, dtype: object

In [119]:
type(df.iloc[22249])

pandas.Series

In [125]:
df.iloc[10:15,0:1]

         Entity
10  Afghanistan
11  Afghanistan
12  Afghanistan
13  Afghanistan
14  Afghanistan