In [1]:
import pandas as pd
import requests

# Fetch the data.
df = pd.read_csv("https://ourworldindata.org/grapher/life-expectancy.csv?v=1&csvType=full&useColumnShortNames=true", storage_options = {'User-Agent': 'Our World In Data data fetch/1.0'})

# Fetch the metadata
metadata = requests.get("https://ourworldindata.org/grapher/life-expectancy.metadata.json?v=1&csvType=full&useColumnShortNames=true").json()

In [3]:
df.head(3)

        entity code  year  life_expectancy_0
0  Afghanistan  AFG  1950            28.1563
1  Afghanistan  AFG  1951            28.5836
2  Afghanistan  AFG  1952            29.0138

In [11]:
df.loc[((df["entity"].str.contains("mex", case=False, regex=True))) & (df["year"]>=1950) & (df["year"]<=1980)]

       entity code  year  life_expectancy_0
12419  Mexico  MEX  1950            43.8357
12420  Mexico  MEX  1951            44.7707
12421  Mexico  MEX  1952            45.6679
12422  Mexico  MEX  1953            47.0446
12423  Mexico  MEX  1954            48.2999
12424  Mexico  MEX  1955            49.5978
12425  Mexico  MEX  1956            50.3553
12426  Mexico  MEX  1957            51.1148
12427  Mexico  MEX  1958            51.8354
12428  Mexico  MEX  1959            52.6611
12429  Mexico  MEX  1960            53.5732
12430  Mexico  MEX  1961            54.4218
12431  Mexico  MEX  1962            55.0573
12432  Mexico  MEX  1963            55.5010
12433  Mexico  MEX  1964            55.9164
12434  Mexico  MEX  1965            56.6876
12435  Mexico  MEX  1966            57.3552
12436  Mexico  MEX  1967            57.9592
12437  Mexico  MEX  1968            58.2202
12438  Mexico  MEX  1969            58.4128
12439  Mexico  MEX  1970            58.8934
12440  Mexico  MEX  1971            59.4148
12441  Mexico  MEX  1972            60.0514
12442  Mexico  MEX  1973            60.5177
12443  Mexico  MEX  1974            61.1799
12444  Mexico  MEX  1975            61.8832
12445  Mexico  MEX  1976            62.4748
12446  Mexico  MEX  1977            62.9879
12447  Mexico  MEX  1978            63.4347
12448  Mexico  MEX  1979            63.8618
12449  Mexico  MEX  1980            64.2819

In [13]:
df.loc[df["entity"].str.contains("South Africa", case=False, regex=True) & (df["year"]>=1950) & (df["year"]<=1980)]

             entity code  year  life_expectancy_0
17856  South Africa  ZAF  1950            43.1094
17857  South Africa  ZAF  1951            44.0558
17858  South Africa  ZAF  1952            45.0469
17859  South Africa  ZAF  1953            46.0535
17860  South Africa  ZAF  1954            47.1192
17861  South Africa  ZAF  1955            48.1727
17862  South Africa  ZAF  1956            49.2144
17863  South Africa  ZAF  1957            50.1955
17864  South Africa  ZAF  1958            51.1486
17865  South Africa  ZAF  1959            51.8817
17866  South Africa  ZAF  1960            52.5751
17867  South Africa  ZAF  1961            53.0669
17868  South Africa  ZAF  1962            53.5657
17869  South Africa  ZAF  1963            53.8947
17870  South Africa  ZAF  1964            54.2147
17871  South Africa  ZAF  1965            54.4272
17872  South Africa  ZAF  1966            54.7315
17873  South Africa  ZAF  1967            54.9553
17874  South Africa  ZAF  1968            55.1915
17875  South Africa  ZAF  1969            55.4399
17876  South Africa  ZAF  1970            55.6808
17877  South Africa  ZAF  1971            56.0196
17878  South Africa  ZAF  1972            56.3767
17879  South Africa  ZAF  1973            56.7198
17880  South Africa  ZAF  1974            57.1097
17881  South Africa  ZAF  1975            57.5906
17882  South Africa  ZAF  1976            58.0003
17883  South Africa  ZAF  1977            58.4800
17884  South Africa  ZAF  1978            58.9911
17885  South Africa  ZAF  1979            59.4725
17886  South Africa  ZAF  1980            59.9605

In [15]:
df["entity"].nunique()

265

In [16]:
df.index

RangeIndex(start=0, stop=21565, step=1)

In [17]:
df.set_index(["code","year"])

                entity  life_expectancy_0
code year
AFG  1950  Afghanistan            28.1563
     1951  Afghanistan            28.5836
     1952  Afghanistan            29.0138
     1953  Afghanistan            29.4521
     1954  Afghanistan            29.6975
...                ...                ...
ZWE  2019     Zimbabwe            61.0603
     2020     Zimbabwe            61.5300
     2021     Zimbabwe            60.1347
     2022     Zimbabwe            62.3601
     2023     Zimbabwe            62.7748

[21565 rows x 2 columns]

In [18]:
df.head(3)

        entity code  year  life_expectancy_0
0  Afghanistan  AFG  1950            28.1563
1  Afghanistan  AFG  1951            28.5836
2  Afghanistan  AFG  1952            29.0138

In [19]:
df.isnull().sum()

entity                  0
code                 1348
year                    0
life_expectancy_0       0
dtype: int64

In [21]:
df.loc[df["code"].isnull()]

                                      entity code  year  life_expectancy_0
375                                 Americas  NaN  1770            34.8000
376                                 Americas  NaN  1830            34.8000
377                                 Americas  NaN  1850            35.1000
378                                 Americas  NaN  1870            35.1000
379                                 Americas  NaN  1900            41.0000
...                                      ...  ...   ...                ...
17703  Small Island Developing States (SIDS)  NaN  2019            72.0847
17704  Small Island Developing States (SIDS)  NaN  2020            71.7761
17705  Small Island Developing States (SIDS)  NaN  2021            69.8938
17706  Small Island Developing States (SIDS)  NaN  2022            72.1257
17707  Small Island Developing States (SIDS)  NaN  2023            72.7255

[1348 rows x 4 columns]

In [28]:
df.loc[df["code"].notnull(),["entity","year","life_expectancy_0"]].head(3)

        entity  year  life_expectancy_0
0  Afghanistan  1950            28.1563
1  Afghanistan  1951            28.5836
2  Afghanistan  1952            29.0138

In [25]:
df.loc[
    df["code"].isnull(),
    df.columns.str.contains("expectancy", case=False, regex=True)
].head(3)

     life_expectancy_0
375               34.8
376               34.8
377               35.1

In [31]:
df.isnull().sum()

entity                  0
code                 1348
year                    0
life_expectancy_0       0
dtype: int64

In [32]:
df.dropna(subset=["code"], inplace=True)
df.isnull().sum()

entity               0
code                 0
year                 0
life_expectancy_0    0
dtype: int64

In [33]:
df.shape

(20217, 4)

In [34]:
df.set_index(["entity", "year"])

                 code  life_expectancy_0
entity      year
Afghanistan 1950  AFG            28.1563
            1951  AFG            28.5836
            1952  AFG            29.0138
            1953  AFG            29.4521
            1954  AFG            29.6975
...               ...                ...
Zimbabwe    2019  ZWE            61.0603
            2020  ZWE            61.5300
            2021  ZWE            60.1347
            2022  ZWE            62.3601
            2023  ZWE            62.7748

[20217 rows x 2 columns]

In [39]:
resultado = (
    df.groupby("entity")["life_expectancy_0"]
    .mean()
    .sort_values(ascending=True)
)
resultado.head(10)

entity
USSR                        32.700000
South Sudan                 37.841631
Sierra Leone                43.189605
Mali                        43.760793
Niger                       44.187513
East Timor                  44.684692
Nigeria                     44.855897
Chad                        45.007786
Central African Republic    45.084431
Malawi                      45.554985
Name: life_expectancy_0, dtype: float64